Repository dnsimple/dnsimple-csharp, pull requests merged in 2020-06, with the labels that each got.

#11 Include ExpiresAt in Domain object in favor of ExpiresOn
  src/dnsimple-test/Services/DomainsTest.cs
  src/dnsimple-test/Services/RegistrarTest.cs
  src/dnsimple-test/fixtures/v2/api/cancelDomainTransfer/success.http
  src/dnsimple-test/fixtures/v2/api/createDomain/created.http
  src/dnsimple-test/fixtures/v2/api/getDomain/success.http
  src/dnsimple-test/fixtures/v2/api/getDomainTransfer/success.http
  src/dnsimple-test/fixtures/v2/api/listDomains/success.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.auto_renewal_disable/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.auto_renewal_enable/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.create/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.delegation_change/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.delete/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.register/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.register/status-started.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.registrant_change/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.renew/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.resolution_disable/example.http
  src/dnsimple-test/fixtures/v2/webhooks/domain.resolution_enable/example.http
  src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.disable/example.http
  src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.enable/example.http
  src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.purchase/example.http
  src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.renew/example.http
  src/dnsimple/Services/Domains.cs
  src/dnsimple/Services/ListOptions/DomainListOptions.cs
Labels: enhancement, ready-for-review

#15 Readme.md fixes
  README.md
Labels: bug, documentation, ready-for-review

#14 Remove Certificate and Domain expiresOn and add Certificate expiresAt
  src/dnsimple-test/Services/CertificatesTest.cs
  src/dnsimple-test/Services/DomainsTest.cs
  src/dnsimple-test/fixtures/v2/api/getCertificate/success.http
  src/dnsimple-test/fixtures/v2/api/issueLetsencryptCertificate/success.http
  src/dnsimple-test/fixtures/v2/api/issueRenewalLetsencryptCertificate/success.http
  src/dnsimple-test/fixtures/v2/api/listCertificates/success.http
  src/dnsimple-test/fixtures/v2/api/purchaseLetsencryptCertificate/success.http
  src/dnsimple-test/fixtures/v2/api/purchaseRenewalLetsencryptCertificate/success.http
  src/dnsimple-test/fixtures/v2/webhooks/certificate.issue/example.http
  src/dnsimple-test/fixtures/v2/webhooks/certificate.remove_private_key/example.http
  src/dnsimple/Services/Certificates.cs
  src/dnsimple/Services/Domains.cs
  src/dnsimple/Services/ListOptions/CertificatesListOptions.cs
Labels: enhancement, ready-for-review

#18 Update CHANGELOG for recently introduced ExpiresAt
  CHANGELOG.md
Labels: documentation, ready-for-review

#16 Removes required Fax on Contact creation
  CHANGELOG.md
  src/dnsimple-test/Services/ContactsTest.cs
  src/dnsimple/Services/Contacts.cs
Labels: bug, ready-for-review
